version: "3"
services:
  auction-website-ui:
    image: auction-website-ui
    build:
      context: ./ui
    ports:
      - 3000:3000
    container_name: auction-website-ui
  auction-website-api:
    image: auction-website-api
    build:
      context: ./api
    ports:
      - 5000:5000
    container_name: auction-website-api
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${POSTGRES_PORT}
    depends_on:
      - auction-website-db
  auction-website-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${POSTGRES_PORT}
    container_name: auction-website-db
    restart: always
    # volumes:
    #   - ./api/database.sql:/docker-entrypoint-initdb.d/init.sql
